In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.decomposition import TruncatedSVD
import random
# import seaborn as sns
import os.path as path
import os
# import matplotlib
# import matplotlib.font_manager
# import matplotlib.pyplot as plt # graphs plotting
# import Bio
from Bio import SeqIO # some BioPython that will come in handy
#matplotlib inline

from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score


# from matplotlib import rc
# # for Arial typefont
# matplotlib.rcParams['font.family'] = 'Arial'

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import svm

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix 

from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from pandas import DataFrame

from sklearn.model_selection import KFold 
from sklearn.model_selection import RepeatedKFold

from sklearn.metrics import confusion_matrix

from numpy import mean

## for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
# matplotlib.rcParams['mathtext.fontset'] = 'cm'

## for LaTeX typefont
# matplotlib.rcParams['mathtext.fontset'] = 'stix'
# matplotlib.rcParams['font.family'] = 'STIXGeneral'

## for another LaTeX typefont
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

# rc('text', usetex = True)

print("done")

done


In [172]:
dataset_nam = "Sixth"

In [173]:
import csv
# read_path = "D:/University/RA/covid_origin/Dataset/dataframe_Host_names_data.csv"
read_path = "D:/University/RA/covid_origin/Dataset/" + str(dataset_nam) + " Dataset/" + str(dataset_nam) + "_dataset_dataframe_Host_names_data.csv"
# read_path = "D:/University/RA/covid_origin/Dataset/Second Dataset/Second_dataset_dataframe_Host_names_data.csv"

host_names_new = []
host_names_ne = []

with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        tmp = row
#         host_names_new.append(', '.join(row))
        host_names_new.append(tmp[0])

In [174]:
np.unique(host_names_new)

array(['B.1.1.214', 'B.1.177.21', 'B.1.221', 'B.1.243', 'B.1.258',
       'B.1.427', 'B.1.596', 'D.2'], dtype='<U10')

In [175]:
final_labels_temp = [] 
for entry in host_names_new:
    if entry == 'B.1':
        final_labels_temp.append(1)
    elif entry == 'B.1.1':
        final_labels_temp.append(2)
    elif entry == 'B.1.1.7':
        final_labels_temp.append(3)
    elif entry == 'B.1.177':
        final_labels_temp.append(4)
    elif entry == 'B.1.2':
        final_labels_temp.append(5)
    elif entry == 'B.1.351':
        final_labels_temp.append(6)
    elif entry == 'B.1.429':
        final_labels_temp.append(7)
    elif entry == 'B.1.526':
        final_labels_temp.append(8)
    elif entry == 'B.1.617.2':
        final_labels_temp.append(9)
    elif entry == 'P.1':
        final_labels_temp.append(10)
    elif entry == 'D.2':
        final_labels_temp.append(11)
    elif entry == 'B.1.1.214':
        final_labels_temp.append(12)
    elif entry == 'B.1.177.21':
        final_labels_temp.append(13)
    elif entry == 'B.1.221':
        final_labels_temp.append(14)
    elif entry == 'B.1.427':
        final_labels_temp.append(15)
    elif entry == 'B.1.243':
        final_labels_temp.append(16)
    elif entry == 'B.1.1.519':
        final_labels_temp.append(17)
    elif entry == 'B.1.160':
        final_labels_temp.append(18)
    elif entry == 'B.1.596':
        final_labels_temp.append(19)
    elif entry == 'B.1.258':
        final_labels_temp.append(20)

In [176]:
idx = pd.Index(final_labels_temp) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = (idx.value_counts())
print(aq)

print(np.unique(final_labels_temp))

Here are all of the viral species in the dataset: 
 5022 entries in total
11    1500
13    1035
12     699
14     696
16     469
20     245
19     201
15     177
dtype: int64
[11 12 13 14 15 16 19 20]


# Reading kernel matrix

In [177]:
read_path = "D:/University/RA/covid_origin/Code/Kernel_approximation/" + str(dataset_nam) + "_Full_dataset_Alligned_with_variants_Kernel_k9_m0_Alphabet_Size21_trial_1.txt"
# read_path = "D:/University/RA/covid_origin/Code/Kernel_approximation/Second_dataset_Alligned_with_variants_Kernel_k6_m3_Alphabet_Size21_trial_1.txt"
# read_path = "D:/University/RA/covid_origin/Code/Kernel_approximation/Alligned_Kernel_k6_m3_Alphabet_Size23_trial_1.txt"

seq_file_small = []
with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        seq_file_small.append(', '.join(row))

In [178]:
final_jernel_mat = []
mat_2 = []
for y in range(0,len(seq_file_small)):
    aa = seq_file_small[y].split(" ")
    tmp_list = []
    for yy in range(0,len(aa)-1):
        tmp_list.append(int(aa[yy]))
    
    final_jernel_mat.append(tmp_list)

In [179]:
len(final_jernel_mat),len(final_labels_temp)

(5022, 5022)

# Read Protein Data

In [180]:
# read_path = "D:/University/RA/JCB_Viral_Host_Classification/Dataset/Alligned_Final_Host_protein_data.csv"

# protein_data_tmp = []
# with open(read_path) as csv_file:
#     csv_reader = csv.reader(csv_file, delimiter=',')
#     for row in csv_reader:
#         protein_data_tmp.append(', '.join(row))

In [181]:
# final_protein_data_tmp = []
# mat_2 = []
# for y in range(0,len(protein_data_tmp)):
#     aa = protein_data_tmp[y].split(",")
#     tmp_list = []
#     for yy in range(0,len(aa)-1):
#         ch = aa[yy]
#         ch_1 = ch.replace(" ","")
#         tmp_list.append(ch_1)
    
#     final_protein_data_tmp.append(tmp_list)

In [182]:
# aq = (final_protein_data_tmp[0])
# aq[1270:1275]

# Classifier Functions

In [183]:
# In[4]
def roc_auc_score_multiclass(actual_class, pred_class, average = "macro"):

    unique_class = set(actual_class)
    roc_auc_dict = {}
    for per_class in unique_class:
        #creating a list of all the classes except the current class 
        other_class = [x for x in unique_class if x != per_class]

        #marking the current class as 1 and all other classes as 0
        new_actual_class = [0 if x in other_class else 1 for x in actual_class]
        new_pred_class = [0 if x in other_class else 1 for x in pred_class]

        #using the sklearn metrics method to calculate the roc_auc_score
        roc_auc = roc_auc_score(new_actual_class, new_pred_class, average = average)
        roc_auc_dict[per_class] = roc_auc
    
    
    check = pd.DataFrame(roc_auc_dict.items())
    return mean(check)

def svm_fun_kernel(X_train,y_train,X_test,y_test,kernel_mat):

#     clf = svm.SVC()
    clf = svm.SVC(kernel=kernel_mat)
    
    #Train the model using the training sets
    clf.fit(kernel_mat, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Kernel Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    
# In[5]
##########################  SVM Classifier  ################################
def svm_fun(X_train,y_train,X_test,y_test):
    #Create a svm Classifier
    clf = svm.SVC(kernel='linear') # Linear Kernel

    #Train the model using the training sets
    clf.fit(X_train, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    


# In[5]
##########################  NB Classifier  ################################
def gaus_nb_fun(X_train,y_train,X_test,y_test):
    gnb = GaussianNB()
    y_pred = gnb.fit(X_train, y_train).predict(X_test)


    NB_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Gaussian NB Accuracy:",NB_acc)

    NB_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Precision:",NB_prec)
    
    NB_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Recall:",NB_recall)
    
    NB_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB F1 weighted:",NB_f1_weighted)
    
    NB_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Gaussian NB F1 macro:",NB_f1_macro)
    
    NB_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Gaussian NB F1 micro:",NB_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix NB : \n", confuse)
    print("NB Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    check = [NB_acc,NB_prec,NB_recall,NB_f1_weighted,NB_f1_macro,NB_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  MLP Classifier  ################################
def mlp_fun(X_train,y_train,X_test,y_test):
    # Feature scaling
    scaler = StandardScaler()  
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)  
    X_test_2 = scaler.transform(X_test)


    # Finally for the MLP- Multilayer Perceptron
    mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
    mlp.fit(X_train, y_train)


    y_pred = mlp.predict(X_test_2)
    
    MLP_acc = metrics.accuracy_score(y_test, y_pred)
#     print("MLP Accuracy:",MLP_acc)
    
    MLP_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("MLP Precision:",MLP_prec)
    
    MLP_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("MLP Recall:",MLP_recall)
    
    MLP_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("MLP F1:",MLP_f1_weighted)
    
    MLP_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("MLP F1:",MLP_f1_macro)
    
    MLP_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("MLP F1:",MLP_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix MLP : \n", confuse)
    print("MLP Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [MLP_acc,MLP_prec,MLP_recall,MLP_f1_weighted,MLP_f1_macro,MLP_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  knn Classifier  ################################
def knn_fun(X_train,y_train,X_test,y_test):
    classifier = KNeighborsClassifier(n_neighbors=5)
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    knn_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Knn Accuracy:",knn_acc)
    
    knn_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Knn Precision:",knn_prec)
    
    knn_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Knn Recall:",knn_recall)
    
    knn_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Knn F1 weighted:",knn_f1_weighted)
    
    knn_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Knn F1 macro:",knn_f1_macro)
    
    knn_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Knn F1 micro:",knn_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix KNN : \n", confuse)
    print("KNN Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [knn_acc,knn_prec,knn_recall,knn_f1_weighted,knn_f1_macro,knn_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  Random Forest Classifier  ################################
def rf_fun(X_train,y_train,X_test,y_test):
    # Import the model we are using
    from sklearn.ensemble import RandomForestClassifier
    # Instantiate model with 1000 decision trees
    rf = RandomForestClassifier(n_estimators = 100)
    # Train the model on training data
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)

    fr_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Random Forest Accuracy:",fr_acc)
    
    fr_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Random Forest Precision:",fr_prec)
    
    fr_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Random Forest Recall:",fr_recall)
    
    fr_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Random Forest F1 weighted:",fr_f1_weighted)
    
    fr_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Random Forest F1 macro:",fr_f1_macro)
    
    fr_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Random Forest F1 micro:",fr_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix RF : \n", confuse)
    print("RF Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [fr_acc,fr_prec,fr_recall,fr_f1_weighted,fr_f1_macro,fr_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
    ##########################  Logistic Regression Classifier  ################################
def lr_fun(X_train,y_train,X_test,y_test):

    model = LogisticRegression(solver='liblinear', random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    LR_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix LR : \n", confuse)
    print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


def fun_decision_tree(X_train,y_train,X_test,y_test):
    from sklearn import tree
    
    clf = tree.DecisionTreeClassifier()    
    clf = clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    dt_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    dt_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    dt_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    dt_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    dt_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    dt_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix DT : \n", confuse)
    print("DT Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [dt_acc,dt_prec,dt_recall,dt_f1_weighted,dt_f1_macro,dt_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


In [184]:
len(final_jernel_mat)

5022

# Kernel PCA

In [185]:
from sklearn.decomposition import KernelPCA

#############  Kernel PCA ################
transformer = KernelPCA(n_components=100, kernel='precomputed')
X_transformed = transformer.fit_transform(final_jernel_mat)
X_transformed.shape
#############  Kernel PCA ################


(5022, 100)

In [186]:
np.unique(final_labels_temp)

array([11, 12, 13, 14, 15, 16, 19, 20])

In [187]:
X = np.array(X_transformed)
y =  np.array(final_labels_temp)

rkf = RepeatedKFold(n_splits=10, n_repeats=1, random_state=None)
# X is the feature set and y is the target
counter = 1
# print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
svm_table = []
gauu_nb_table = []
mlp_table = []
knn_table = []
rf_table = []
lr_table = []
dt_table = []

Fold_counter = 1
for train_index, test_index in rkf.split(X):
    print("Fold_counter = ",Fold_counter,"  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    Fold_counter = Fold_counter+1
    
    counter = counter+1
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    
    gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
    mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
    knn_return = knn_fun(X_train,y_train,X_test,y_test)
    rf_return = rf_fun(X_train,y_train,X_test,y_test)
    lr_return = lr_fun(X_train,y_train,X_test,y_test)
    dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
    svm_return = svm_fun(X_train,y_train,X_test,y_test)
#     svm_return = svm_fun_kernel(X_train,y_train,X_test,y_test,final_jernel_mat)

    
    gauu_nb_table.append(gauu_nb_return)
    mlp_table.append(mlp_return)
    knn_table.append(knn_return)
    rf_table.append(rf_return)
    lr_table.append(lr_return)
    dt_table.append(dt_return)
    svm_table.append(svm_return)
     
svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


Fold_counter =  1   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Confusion Matrix NB : 
 [[150   0   0   0  11   1   0   0]
 [  6  53   0   0   1   7   0   0]
 [  7   0  94   0   1   1   1   0]
 [  4   0   0  56   8   0   1   0]
 [  0   0   0   0  14   0   0   0]
 [  0  30   0   0   4   8   1   0]
 [  0   6   0   0   5   0  10   0]
 [  0   0   0   0   3   0   0  20]]
NB Class Wise Accuracy :  [0.92592593 0.79104478 0.90384615 0.8115942  1.         0.18604651
 0.47619048 0.86956522]
Confusion Matrix MLP : 
 [[158   0   1   0   0   0   3   0]
 [  0  62   0   0   0   5   0   0]
 [  0   0 104   0   0   0   0   0]
 [  2   0   0  65   0   0   2   0]
 [  0   0   0   0  14   0   0   0]
 [  0  13   1   1   0  28   0   0]
 [  0   6   1   0   0   1  13   0]
 [  1   0   0   0   0   0   0  22]]
MLP Class Wise Accuracy :  [0.97530864 0.92537313 1.         0.94202899 1.         0.65116279
 0.61904762 0.95652174]
Confusion Matrix KNN : 
 [[161   0   0   0   0   1   0   0]
 [  0  67 

In [188]:
idx = pd.Index(host_names_new) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = (idx.value_counts())
print(aq)

print(np.unique(host_names_new))

Here are all of the viral species in the dataset: 
 5022 entries in total
D.2           1500
B.1.177.21    1035
B.1.1.214      699
B.1.221        696
B.1.243        469
B.1.258        245
B.1.596        201
B.1.427        177
dtype: int64
['B.1.1.214' 'B.1.177.21' 'B.1.221' 'B.1.243' 'B.1.258' 'B.1.427'
 'B.1.596' 'D.2']


In [189]:
# print(svm_table_final)
# print(gauu_nb_table_final)
# print(mlp_table_final)
# print(knn_table_final)
# print(rf_table_final)
# print(lr_table_final)

#taking average of all k-fold performance values
final_mean_mat = []

final_mean_mat.append(np.transpose((list(svm_table_final.mean()))))
final_mean_mat.append(np.transpose((list(gauu_nb_table_final.mean()))))
final_mean_mat.append(np.transpose((list(mlp_table_final.mean()))))
final_mean_mat.append(np.transpose((list(knn_table_final.mean()))))
final_mean_mat.append(np.transpose((list(rf_table_final.mean()))))
final_mean_mat.append(np.transpose((list(lr_table_final.mean()))))
final_mean_mat.append(np.transpose((list(dt_table_final.mean()))))

final_avg_mat = DataFrame(final_mean_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["SVM","NB","MLP","KNN","RF","LR","DT"])

final_avg_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
SVM  0.941657   0.946917  0.941657       0.939457    0.910634    0.941657   
NB   0.828159   0.845810  0.828159       0.820077    0.754405    0.828159   
MLP  0.923731   0.928017  0.923731       0.921444    0.883468    0.923731   
KNN  0.920746   0.925487  0.920746       0.916827    0.880373    0.920746   
RF   0.940658   0.945848  0.940658       0.937884    0.907553    0.940658   
LR   0.946235   0.951945  0.946235       0.943989    0.919215    0.946235   
DT   0.925126   0.929029  0.925126       0.922795    0.884587    0.925126   

      ROC AUC  
SVM  0.946546  
NB   0.883695  
MLP  0.931433  
KNN  0.923524  
RF   0.942208  
LR   0.949756  
DT   0.932658

In [190]:
#taking average of all k-fold performance values
final_std_mat = []

final_std_mat.append(np.transpose((list(svm_table_final.std()))))
final_std_mat.append(np.transpose((list(gauu_nb_table_final.std()))))
final_std_mat.append(np.transpose((list(mlp_table_final.std()))))
final_std_mat.append(np.transpose((list(knn_table_final.std()))))
final_std_mat.append(np.transpose((list(rf_table_final.std()))))
final_std_mat.append(np.transpose((list(lr_table_final.std()))))
final_std_mat.append(np.transpose((list(dt_table_final.std()))))

final_stdd_mat = DataFrame(final_std_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["SVM","NB","MLP","KNN","RF","LR","DT"])

final_stdd_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
SVM  0.006708   0.005654  0.006708       0.006983    0.013090    0.006708   
NB   0.017433   0.012807  0.017433       0.015347    0.027118    0.017433   
MLP  0.011019   0.010724  0.011019       0.011788    0.015055    0.011019   
KNN  0.011085   0.011124  0.011085       0.010807    0.015339    0.011085   
RF   0.006175   0.005858  0.006175       0.006598    0.012254    0.006175   
LR   0.007343   0.007452  0.007343       0.007889    0.013718    0.007343   
DT   0.008542   0.008826  0.008542       0.008788    0.012479    0.008542   

      ROC AUC  
SVM  0.008387  
NB   0.013704  
MLP  0.009284  
KNN  0.008611  
RF   0.006628  
LR   0.008003  
DT   0.008805

# Train-Test Split

In [191]:
# X = np.array(final_jernel_mat)
# y =  np.array(final_labels_temp)


# # print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
# svm_table = []
# gauu_nb_table = []
# mlp_table = []
# knn_table = []
# rf_table = []
# lr_table = []
# dt_table = []

# from sklearn.model_selection import ShuffleSplit # or StratifiedShuffleSplit
# sss = ShuffleSplit(n_splits=1, test_size=0.3)
# sss.get_n_splits(X, y)
# train_index, test_index = next(sss.split(X, y)) 

# X_train, X_test = X[train_index], X[test_index]
# y_train, y_test = y[train_index], y[test_index]


# gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
# mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
# knn_return = knn_fun(X_train,y_train,X_test,y_test)
# rf_return = rf_fun(X_train,y_train,X_test,y_test)
# lr_return = lr_fun(X_train,y_train,X_test,y_test)
# dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
# #     svm_return = svm_fun(X_train,y_train,X_test,y_test)
# #     svm_return = svm_fun_kernel(X_train,y_train,X_test,y_test,final_jernel_mat)


# gauu_nb_table.append(gauu_nb_return)
# mlp_table.append(mlp_return)
# knn_table.append(knn_return)
# rf_table.append(rf_return)
# lr_table.append(lr_return)
# dt_table.append(dt_return)
# #     svm_table.append(svm_return)
     
# # svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

# dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


# Adaboost

In [192]:
# from sklearn.ensemble import AdaBoostClassifier
# from sklearn.datasets import make_classification
# # >>> X, y = make_classification(n_samples=1000, n_features=4,
# # ...                            n_informative=2, n_redundant=0,
# # ...                            random_state=0, shuffle=False)

# X = np.array(final_jernel_mat)
# y =  np.array(final_labels_temp)

# X_train , X_test , y_train, y_test = train_test_split(X, y, random_state=0)



In [193]:
# clf = AdaBoostClassifier(n_estimators=100, random_state=0)
# clf.fit(X_train, y_train)


In [194]:
# # AdaBoostClassifier(n_estimators=100, random_state=0)
# y_pred = clf.predict(X_test)
# # clf.score(y_test, y_pred)

In [195]:
# LR_acc = metrics.accuracy_score(y_test, y_pred)
# #     print("Logistic Regression Accuracy:",LR_acc)

# LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
# #     print("Logistic Regression Precision:",LR_prec)

# LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
# #     print("Logistic Regression Recall:",LR_recall)

# LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
# #     print("Logistic Regression F1 weighted:",LR_f1_weighted)

# LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
# #     print("Logistic Regression F1 macro:",LR_f1_macro)

# LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
# #     print("Logistic Regression F1 micro:",LR_f1_micro)

# confuse = confusion_matrix(y_test, y_pred)
# print("Confusion Matrix LR : \n", confuse)
# print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
# ######################## Compute ROC curve and ROC area for each class ################
# y_prob = y_pred
# macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')

# check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]

# print(check)

In [196]:
# uniqueWords = np.unique(final_protein_data_tmp)

In [197]:
# uniqueWords_2 = list(uniqueWords)
# uniqueWords

In [198]:
# final_freq_vec = []
# for ind_freq in range(len(final_protein_data_tmp)):
#     print(ind_freq,"/",len(final_protein_data_tmp))
#     temp_freq_vec = [0]* len(uniqueWords)
#     aaa = final_protein_data_tmp[ind_freq]
#     for i in range(len(aaa)):
#         ind = uniqueWords_2.index(aaa[i])
#         temp_freq_vec[ind] = temp_freq_vec[ind] + 1
#     final_freq_vec.append(temp_freq_vec)

In [199]:
# len(final_freq_vec[0])

In [200]:
# X_train , X_test , y_train, y_test = train_test_split(X_transformed, host_names_new, random_state=0)

# clf = svm.SVC(kernel="linear")

# clf.fit(X_train,y_train)



In [201]:
# y_pred = clf.predict(X_test)


# LR_acc = metrics.accuracy_score(y_test, y_pred)
# #     print("Logistic Regression Accuracy:",LR_acc)

# LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
# #     print("Logistic Regression Precision:",LR_prec)

# LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
# #     print("Logistic Regression Recall:",LR_recall)

# LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
# #     print("Logistic Regression F1 weighted:",LR_f1_weighted)

# LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
# #     print("Logistic Regression F1 macro:",LR_f1_macro)

# LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
# #     print("Logistic Regression F1 micro:",LR_f1_micro)

# confuse = confusion_matrix(y_test, y_pred)
# print("Confusion Matrix LR : \n", confuse)
# print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
# ######################## Compute ROC curve and ROC area for each class ################

# y_prob = y_pred
# macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')

# check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]

# print(check)

In [202]:
# print(__doc__)

# import numpy as np
# import matplotlib.pyplot as plt
# from sklearn import svm, datasets

# # import some data to play with
# iris = datasets.load_iris()
# X = iris.data[:, :2]  # we only take the first two features. We could
#                       # avoid this ugly slicing by using a two-dim dataset
# Y = iris.target


# def my_kernel(X, Y):
#     """
#     We create a custom kernel:

#                  (2  0)
#     k(X, Y) = X  (    ) Y.T
#                  (0  1)
#     """
#     M = np.array([[2, 0], [0, 1.0]])
#     return np.dot(np.dot(X, M), Y.T)

# aqq = my_kernel
# aqq




In [203]:
# h = .02  # step size in the mesh

# # we create an instance of SVM and fit out data.
# clf = svm.SVC(kernel=my_kernel)
# clf.fit(X, Y)

In [204]:
# # Plot the decision boundary. For that, we will assign a color to each
# # point in the mesh [x_min, x_max]x[y_min, y_max].
# x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
# y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
# xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
# Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

# # Put the result into a color plot
# Z = Z.reshape(xx.shape)
# plt.pcolormesh(xx, yy, Z, cmap=plt.cm.Paired)

# # Plot also the training points
# plt.scatter(X[:, 0], X[:, 1], c=Y, cmap=plt.cm.Paired, edgecolors='k')
# plt.title('3-Class classification using Support Vector Machine with custom'
#           ' kernel')
# plt.axis('tight')
# plt.show()