In [54]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.decomposition import TruncatedSVD
import random
# import seaborn as sns
import os.path as path
import os
# import matplotlib
# import matplotlib.font_manager
# import matplotlib.pyplot as plt # graphs plotting
# import Bio
from Bio import SeqIO # some BioPython that will come in handy
#matplotlib inline

from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score


# from matplotlib import rc
# # for Arial typefont
# matplotlib.rcParams['font.family'] = 'Arial'

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import svm

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix 

from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from pandas import DataFrame

from sklearn.model_selection import KFold 
from sklearn.model_selection import RepeatedKFold

from sklearn.metrics import confusion_matrix

from numpy import mean

## for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
# matplotlib.rcParams['mathtext.fontset'] = 'cm'

## for LaTeX typefont
# matplotlib.rcParams['mathtext.fontset'] = 'stix'
# matplotlib.rcParams['font.family'] = 'STIXGeneral'

## for another LaTeX typefont
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

# rc('text', usetex = True)

print("done")

done


In [132]:
dataset_nam = "Sixth"

In [133]:
import csv
# read_path = "D:/University/RA/covid_origin/Dataset/dataframe_Host_names_data.csv"
# read_path = "D:/University/RA/covid_origin/Dataset/First Dataset/First_dataset_dataframe_Host_names_data.csv"
read_path = "D:/University/RA/covid_origin/Dataset/" + str(dataset_nam) + " Dataset/" + str(dataset_nam) + "_dataset_dataframe_Host_names_data.csv"

host_names_new = []
# host_names_ne = []

with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        tmp = row
#         host_names_new.append(', '.join(row))
        host_names_new.append(tmp[0])

In [134]:
final_labels_temp = [] 
for entry in host_names_new:
    if entry == 'B.1':
        final_labels_temp.append(1)
    elif entry == 'B.1.1':
        final_labels_temp.append(2)
    elif entry == 'B.1.1.7':
        final_labels_temp.append(3)
    elif entry == 'B.1.177':
        final_labels_temp.append(4)
    elif entry == 'B.1.2':
        final_labels_temp.append(5)
    elif entry == 'B.1.351':
        final_labels_temp.append(6)
    elif entry == 'B.1.429':
        final_labels_temp.append(7)
    elif entry == 'B.1.526':
        final_labels_temp.append(8)
    elif entry == 'B.1.617.2':
        final_labels_temp.append(9)
    elif entry == 'P.1':
        final_labels_temp.append(10)
    elif entry == 'D.2':
        final_labels_temp.append(11)
    elif entry == 'B.1.1.214':
        final_labels_temp.append(12)
    elif entry == 'B.1.177.21':
        final_labels_temp.append(13)
    elif entry == 'B.1.221':
        final_labels_temp.append(14)
    elif entry == 'B.1.427':
        final_labels_temp.append(15)
    elif entry == 'B.1.243':
        final_labels_temp.append(16)
    elif entry == 'B.1.1.519':
        final_labels_temp.append(17)
    elif entry == 'B.1.160':
        final_labels_temp.append(18)
    elif entry == 'B.1.596':
        final_labels_temp.append(19)
    elif entry == 'B.1.258':
        final_labels_temp.append(20)

In [135]:
import csv
# read_path = "D:/University/RA/covid_origin/Dataset/dataframe_Host_names_data.csv"
# read_path = "D:/University/RA/covid_origin/Dataset/First Dataset/First_dataset_Alligned_Host_protein_data_with_variants.csv"
read_path = "D:/University/RA/covid_origin/Dataset/" + str(dataset_nam) + " Dataset/" + str(dataset_nam) + "_dataset_Alligned_Host_protein_data_with_variants.csv"
# read_path = "D:/University/RA/covid_origin/Dataset/Second Dataset/Second_dataset_dataframe_Host_names_data.csv"

prot_seq = []
# host_names_ne = []

with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        tmp = row
#         host_names_new.append(', '.join(row))
        prot_seq.append(tmp)

In [136]:
(np.unique(prot_seq[1]))

array(['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P',
       'Q', 'R', 'S', 'T', 'V', 'W', 'Y'], dtype='<U1')

In [137]:
# We create a class fasta_sequence so that we would be able to use the sequence data easily 

class fasta_sequence:
    def __init__(self, sequence, type_of_encoding = "onehot"):
        
        # we read the input data
        
        self.sequence = sequence
        
        # and create more descriptions of the input data
        
#         # report the strain name (the 1st fiel of the defline)
# #         self.strain_name = defline.split("|")[0]
#         # report the accession number (the 2nd fiel of the defline)
#         self.host_species = defline.split(":")[len(defline.split(":"))-1]        
# #         # report the host species (the 3rd fiel of the defline)
# #         self.host_species = defline.split("|")[2]    
# #         # report the virus species (the 4th fiel of the defline)
# #         self.virus_species = defline.split("|")[3]
        
        
# We convert a string with the alphabet = 'ABCDEFGHIJKLMNPQRSTUVWXYZ-' 
# into either a list mapping chars to integers (called integer encoding),
# or a sparce list. In the latter, each amino acid is represented as an one-hot vector of length 25, 
# where each position, except one, is set to 0.  E.g., alanine is encoded as 10000000000000000000, 
# cystine is encoded as 01000000000000000000
# See the full table above.
# Symbol '-' is encoded as a zero-vector.

        def encoding(sequence, type_of_encoding):

            # define universe of possible input values
#             alphabet = 'ABCDEFGHIJKLMNPQRSTUVWXYZ-'
            alphabet = 'ACDEFGHIKLMNPQRSTVWXY-'
            # define a mapping of chars to integers
            char_to_int = dict((c, i) for i, c in enumerate(alphabet))


            # integer encoding
            integer_encoded = [char_to_int[char] for char in sequence]

            # one-hot encoding
            onehot_encoded = list()
            for value in integer_encoded:
                letter = [0 for _ in range(len(alphabet)-1)]
                if value != len(alphabet)-1:
                    letter[value] = 1
                onehot_encoded.append(letter)
            flat_list = [item for sublist in onehot_encoded for item in sublist]

            if type_of_encoding == "onehot":
                return flat_list
            else:
                return integer_encoded
            
        #  we use the encoding function to create a new attribute for the sequence -- its encoding        
        self.encoded = encoding(sequence, type_of_encoding)
        
print("done")

done


In [138]:
# we create a list of sequences as objects of the class fasta_sequence
# all sequences are encoded with one-hot encoding (it is the default option of the constructor of the class)
sequences = []
for i in range(0, len(prot_seq)):
    current_sequence = fasta_sequence(prot_seq[i])
    sequences.append(current_sequence)
    
print("done")

done


In [139]:
# for a list of sequences, returns a list of encoded sequences and a list of targets

def EncodeAndTarget(list_of_sequences):
    # encoding the sequences
    list_of_encoded_sequences = [entry.encoded for entry in list_of_sequences]
    return list_of_encoded_sequences   



In [140]:
encoded_sequences = EncodeAndTarget(sequences)

In [141]:
len(encoded_sequences[0])

26733

In [142]:
# calculates explained variance for each of elements in number_of_components
def list_of_explained_variances(sequences, number_of_components, to_print = False):
    levels = []
    for i in number_of_components:
        svd = TruncatedSVD(n_components = i, n_iter = 7, random_state = 42)
        X = svd.fit_transform(sequences)
        explained_variances = svd.explained_variance_ratio_
        
        # the sum of all included explained variances 
        the_level = explained_variances.sum()
        if to_print == True:
            print(i, the_level)
        levels.append(the_level)
    return levels

In [143]:
number_of_components = list(range(100,201)) # + [150,200,300,500,1000]


In [144]:
# levels = list_of_explained_variances(encoded_sequences, number_of_components, to_print = True)

In [145]:
# levels

In [146]:
# levels_vals = [0.294532521783316,0.4431541223551866,0.5486556314783586,0.609962650582966,0.6642488530360086,0.6915160090926539,0.7164802500571719,0.736060007300107,0.7540205391622652,0.7703735594256091,0.7853353687470317,0.7972992423938484,0.8074179810355626,0.8158338148036887,0.8234054713697401,0.8300849371875492,0.8360895370837929,0.8417984510384396,0.8474498397886968,0.8528383872091027,0.8574457181687388,0.8617508387675202,0.8656572707018166,0.869445621310984,0.8729566924767909,0.8763872349639464,0.8794135037160155,0.8823251203515432,0.885206173961614,0.8879568039938939,0.8904085950256445,0.892747918826147,0.8950052495560766,0.8972512471533531,0.8993983155769976,0.9014756065148252,0.9034313573740042,0.9052733898918198,0.9070869422244264,0.9088116367192489,0.9104645337684056,0.9120344220373385,0.9135630143221701,0.9150740972941204,0.9164747930259688,0.9178067614893676,0.9190706860257716,0.9202997605235431,0.9215204817469101,0.9226690120231316,0.9238295725146132,0.9249244932869135,0.9259932809676948,0.9270297380812844,0.9280151685228677,0.928994966385677,0.9299373687328369,0.9308436288802525,0.9317246217743221,0.9325961098306486,0.9334292161668962,0.9342697775988066,0.9350874353975188,0.9358941073930227,0.9366933261338775,0.9374691358052238,0.9382139827404798,0.9389546195428078,0.9396738513927256,0.9403759988598417,0.9410461444773179,0.9416579917211966,0.9423355596055751,0.9429531118554599,0.9435720971629734,0.944162610899261,0.944748457518669,0.9453189040304593,0.9458859664670657,0.9464353812218903,0.9469640379642932,0.9475218344345109,0.9480403053664795,0.9485299096463202,0.949075739821613,0.9495773427050426,0.9500665885897673,0.9505452848203714,0.9509988014508934,0.9514793180689595,0.9519181848042253,0.9523691091852947,0.9527936834518198,0.9532199552326225,0.9536403374387319,0.9540442280802733,0.9544535261711223,0.9548565811776244,0.955233593632691,0.955233593632691,0.9556222623600944,0.9560027202570945,0.956377312926549,0.9567246370307108,0.9571094080638415,0.9574513302750038,0.9577899656297726,0.9581386578532396,0.9584740515261899,0.9588030660869415,0.9591382882228973,0.9594574453865525,0.9597631247288768,0.9600860377681912,0.960402476400569,0.9606928009262147,0.9610009359004076,0.9613003914401387,0.961584831691844,0.9618733721634917,0.962147002308417,0.9624342850617855,0.9627085760266789,0.9629741304433314,0.9632528017469565,0.9635164731291592,0.9637738697826905,0.9640274591620865,0.9642847936930564,0.9645289632191162,0.9647722598483647,0.9650353290349021,0.9652710086967561,0.9655203277387981,0.9657593449038835,0.9659976531938403,0.966225406163312,0.9664718534267597,0.9666988847841123,0.9669182870139795,0.9671343557309128,0.9673522719110941,0.9675834293618489,0.9677951528042511,0.9680075125892411,0.968209361065858,0.9684230398272341,0.9686251172592225,0.9688331048896281,0.9690285652450599,0.9692369474197952,0.969406217132558,0.9696068591531481,0.9698070454568908,0.969996241362984,0.9701768890458105,0.970370221182847,0.9705360600144128,0.9707285042522052,0.9709011384322151,0.9710858189397507,0.9712616142178367,0.971435572423862,0.9716110031550584,0.9717647169284809,0.9719249378538871,0.9721040500263588,0.9722620994828455,0.9724262555513754,0.972590767595849,0.9727466061792047,0.9729097088742019,0.9730692137101977,0.9732143596185384,0.9733787742591354,0.9735266737077336,0.973678699230674,0.9738286982787421,0.9739733876699115,0.974120990429454,0.974258984849405,0.9744172061349782,0.9745520235885543,0.9746901914797048,0.9748357849502488,0.9749646993853559,0.9751096434304816,0.9752449959306435,0.9753787456955798,0.9755071000007441,0.97564170576703,0.9757788025244971,0.975896341031587,0.9760334903643846,0.9761588200167628,0.9762849445250088,0.9764070614680083,0.9765358742261858,0.9766533322324739,0.9767781588165625]

In [147]:
# import matplotlib.pyplot as plt
# plt.plot(levels_vals)

In [148]:
svd = TruncatedSVD(n_components = 100, n_iter = 7, random_state = 42)
data_with_svd = svd.fit_transform(encoded_sequences)


explained_variances = svd.explained_variance_ratio_

the_level = explained_variances.sum()

In [149]:
# In[4]
def roc_auc_score_multiclass(actual_class, pred_class, average = "macro"):

    unique_class = set(actual_class)
    roc_auc_dict = {}
    for per_class in unique_class:
        #creating a list of all the classes except the current class 
        other_class = [x for x in unique_class if x != per_class]

        #marking the current class as 1 and all other classes as 0
        new_actual_class = [0 if x in other_class else 1 for x in actual_class]
        new_pred_class = [0 if x in other_class else 1 for x in pred_class]

        #using the sklearn metrics method to calculate the roc_auc_score
        roc_auc = roc_auc_score(new_actual_class, new_pred_class, average = average)
        roc_auc_dict[per_class] = roc_auc
    
    
    check = pd.DataFrame(roc_auc_dict.items())
    return mean(check)

def svm_fun_kernel(X_train,y_train,X_test,y_test,kernel_mat):

#     clf = svm.SVC()
    clf = svm.SVC(kernel=kernel_mat)
    
    #Train the model using the training sets
    clf.fit(kernel_mat, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Kernel Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    
# In[5]
##########################  SVM Classifier  ################################
def svm_fun(X_train,y_train,X_test,y_test):
    #Create a svm Classifier
    clf = svm.SVC(kernel='linear') # Linear Kernel

    #Train the model using the training sets
    clf.fit(X_train, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    


# In[5]
##########################  NB Classifier  ################################
def gaus_nb_fun(X_train,y_train,X_test,y_test):
    gnb = GaussianNB()
    y_pred = gnb.fit(X_train, y_train).predict(X_test)


    NB_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Gaussian NB Accuracy:",NB_acc)

    NB_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Precision:",NB_prec)
    
    NB_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Recall:",NB_recall)
    
    NB_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB F1 weighted:",NB_f1_weighted)
    
    NB_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Gaussian NB F1 macro:",NB_f1_macro)
    
    NB_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Gaussian NB F1 micro:",NB_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix NB : \n", confuse)
    print("NB Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    check = [NB_acc,NB_prec,NB_recall,NB_f1_weighted,NB_f1_macro,NB_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  MLP Classifier  ################################
def mlp_fun(X_train,y_train,X_test,y_test):
    # Feature scaling
    scaler = StandardScaler()  
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)  
    X_test_2 = scaler.transform(X_test)


    # Finally for the MLP- Multilayer Perceptron
    mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
    mlp.fit(X_train, y_train)


    y_pred = mlp.predict(X_test_2)
    
    MLP_acc = metrics.accuracy_score(y_test, y_pred)
#     print("MLP Accuracy:",MLP_acc)
    
    MLP_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("MLP Precision:",MLP_prec)
    
    MLP_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("MLP Recall:",MLP_recall)
    
    MLP_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("MLP F1:",MLP_f1_weighted)
    
    MLP_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("MLP F1:",MLP_f1_macro)
    
    MLP_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("MLP F1:",MLP_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix MLP : \n", confuse)
    print("MLP Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [MLP_acc,MLP_prec,MLP_recall,MLP_f1_weighted,MLP_f1_macro,MLP_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  knn Classifier  ################################
def knn_fun(X_train,y_train,X_test,y_test):
    classifier = KNeighborsClassifier(n_neighbors=5)
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    knn_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Knn Accuracy:",knn_acc)
    
    knn_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Knn Precision:",knn_prec)
    
    knn_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Knn Recall:",knn_recall)
    
    knn_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Knn F1 weighted:",knn_f1_weighted)
    
    knn_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Knn F1 macro:",knn_f1_macro)
    
    knn_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Knn F1 micro:",knn_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix KNN : \n", confuse)
    print("KNN Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [knn_acc,knn_prec,knn_recall,knn_f1_weighted,knn_f1_macro,knn_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  Random Forest Classifier  ################################
def rf_fun(X_train,y_train,X_test,y_test):
    # Import the model we are using
    from sklearn.ensemble import RandomForestClassifier
    # Instantiate model with 1000 decision trees
    rf = RandomForestClassifier(n_estimators = 100)
    # Train the model on training data
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)

    fr_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Random Forest Accuracy:",fr_acc)
    
    fr_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Random Forest Precision:",fr_prec)
    
    fr_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Random Forest Recall:",fr_recall)
    
    fr_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Random Forest F1 weighted:",fr_f1_weighted)
    
    fr_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Random Forest F1 macro:",fr_f1_macro)
    
    fr_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Random Forest F1 micro:",fr_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix RF : \n", confuse)
    print("RF Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [fr_acc,fr_prec,fr_recall,fr_f1_weighted,fr_f1_macro,fr_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
    ##########################  Logistic Regression Classifier  ################################
def lr_fun(X_train,y_train,X_test,y_test):

    model = LogisticRegression(solver='liblinear', random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    LR_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix LR : \n", confuse)
    print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


def fun_decision_tree(X_train,y_train,X_test,y_test):
    from sklearn import tree
    
    clf = tree.DecisionTreeClassifier()    
    clf = clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    dt_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    dt_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    dt_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    dt_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    dt_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    dt_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix DT : \n", confuse)
    print("DT Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [dt_acc,dt_prec,dt_recall,dt_f1_weighted,dt_f1_macro,dt_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


In [150]:
len(final_labels_temp)

5022

In [151]:
X = np.array(data_with_svd)
# X = np.array(encoded_sequences)
y =  np.array(final_labels_temp)

rkf = RepeatedKFold(n_splits=10, n_repeats=1, random_state=None)
# X is the feature set and y is the target
counter = 1
# print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
svm_table = []
gauu_nb_table = []
mlp_table = []
knn_table = []
rf_table = []
lr_table = []
dt_table = []

for train_index, test_index in rkf.split(X):
    print("Start!!")
    counter = counter+1
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    
    gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
    mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
    knn_return = knn_fun(X_train,y_train,X_test,y_test)
    rf_return = rf_fun(X_train,y_train,X_test,y_test)
    lr_return = lr_fun(X_train,y_train,X_test,y_test)
    dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
    svm_return = svm_fun(X_train,y_train,X_test,y_test)

    
    gauu_nb_table.append(gauu_nb_return)
    mlp_table.append(mlp_return)
    knn_table.append(knn_return)
    rf_table.append(rf_return)
    lr_table.append(lr_return)
    dt_table.append(dt_return)
    svm_table.append(svm_return)
     
svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


Start!!
Confusion Matrix NB : 
 [[33  0 82  1  5 13  9  0]
 [ 0 86  0  0  0  1  0  0]
 [ 0  0 94  0  3  0  0  0]
 [ 0  0 55  9  2  1  0  0]
 [ 0  0  0  0 10  3  1  0]
 [ 1 13  0  0  3 31  2  0]
 [ 0  4  0  6  1  1  5  0]
 [ 1  0  0  0  2  0  0 25]]
NB Class Wise Accuracy :  [0.23076923 0.98850575 0.96907216 0.13432836 0.71428571 0.62
 0.29411765 0.89285714]
Confusion Matrix MLP : 
 [[142   0   0   1   0   0   0   0]
 [  0  86   0   0   0   1   0   0]
 [  0   0  96   0   0   1   0   0]
 [  0   0   0  66   0   0   0   1]
 [  0   0   1   1  10   0   1   1]
 [  0  14   0   2   0  32   2   0]
 [  0   4   0   0   0   0  13   0]
 [  0   0   0   0   0   1   0  27]]
MLP Class Wise Accuracy :  [0.99300699 0.98850575 0.98969072 0.98507463 0.71428571 0.64
 0.76470588 0.96428571]
Confusion Matrix KNN : 
 [[143   0   0   0   0   0   0   0]
 [  0  87   0   0   0   0   0   0]
 [  0   0  96   0   0   0   0   1]
 [  0   0   1  66   0   0   0   0]
 [  1   0   0   0  13   0   0   0]
 [  4  14   0   0   0 

In [152]:
#taking average of all k-fold performance values
final_mean_mat = []

final_mean_mat.append(np.transpose((list(svm_table_final.mean()))))
final_mean_mat.append(np.transpose((list(gauu_nb_table_final.mean()))))
final_mean_mat.append(np.transpose((list(mlp_table_final.mean()))))
final_mean_mat.append(np.transpose((list(knn_table_final.mean()))))
final_mean_mat.append(np.transpose((list(rf_table_final.mean()))))
final_mean_mat.append(np.transpose((list(lr_table_final.mean()))))
final_mean_mat.append(np.transpose((list(dt_table_final.mean()))))

final_avg_mat = DataFrame(final_mean_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["SVM","NB","MLP","KNN","RF","LR","DT"])

final_avg_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
SVM  0.937870   0.945918  0.937870       0.934109    0.905329    0.937870   
NB   0.558542   0.687003  0.558542       0.516809    0.535866    0.558542   
MLP  0.925724   0.930098  0.925724       0.922693    0.883247    0.925724   
KNN  0.923731   0.934026  0.923731       0.920065    0.885355    0.923731   
RF   0.931103   0.937447  0.931103       0.926776    0.891587    0.931103   
LR   0.938070   0.946563  0.938070       0.934498    0.904623    0.938070   
DT   0.923735   0.927162  0.923735       0.920669    0.873722    0.923735   

      ROC AUC  
SVM  0.942340  
NB   0.758260  
MLP  0.931197  
KNN  0.929904  
RF   0.929752  
LR   0.942545  
DT   0.926746

In [153]:
#taking average of all k-fold performance values
final_std_mat = []

final_std_mat.append(np.transpose((list(svm_table_final.std()))))
final_std_mat.append(np.transpose((list(gauu_nb_table_final.std()))))
final_std_mat.append(np.transpose((list(mlp_table_final.std()))))
final_std_mat.append(np.transpose((list(knn_table_final.std()))))
final_std_mat.append(np.transpose((list(rf_table_final.std()))))
final_std_mat.append(np.transpose((list(lr_table_final.std()))))
final_std_mat.append(np.transpose((list(dt_table_final.std()))))

final_stdd_mat = DataFrame(final_std_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["SVM","NB","MLP","KNN","RF","LR","DT"])

final_stdd_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
SVM  0.011233   0.010665  0.011233       0.012535    0.019889    0.011233   
NB   0.030194   0.024798  0.030194       0.034772    0.030138    0.030194   
MLP  0.014652   0.015934  0.014652       0.015354    0.022785    0.014652   
KNN  0.019397   0.011141  0.019397       0.018579    0.023565    0.019397   
RF   0.008771   0.008846  0.008771       0.009565    0.014414    0.008771   
LR   0.010819   0.010738  0.010819       0.011777    0.018283    0.010819   
DT   0.009443   0.009640  0.009443       0.009736    0.015149    0.009443   

      ROC AUC  
SVM  0.010220  
NB   0.016485  
MLP  0.011548  
KNN  0.010450  
RF   0.007832  
LR   0.009440  
DT   0.009061